---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: webserver-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: webserver
          image: webserver:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: FLASK_APP
              value: webserver.py
            - name: AUTHOR
              value: "Сергей Андреевич Н." 
            - name: UUID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 30